apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/argocd/https_username
    name: HTTPS_USERNAME
  - key: zpa-kubeflow-dev/argocd/https_password
    name: HTTPS_PASSWORD
