kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
data:
  DB_NAME_PIPELINES: mlpipeline
  DB_NAME_CACHE: cachedb
  DB_NAME_METADATA: metadb
  RDS_HOST: zpa-kubeflow-dev-instance.xzyabc123456.eu-central-1.rds.amazonaws.com
  RDS_PORT: "3306"
