apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/kubeflow/s3_accesskey
    name: S3_ACCESSKEY
  - key: zpa-kubeflow-dev/kubeflow/s3_secretkey
    name: S3_SECRETKEY
