apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/auth/client_id
    name: client-id
  - key: zpa-kubeflow-dev/auth/client_secret
    name: client-secret
  - key: zpa-kubeflow-dev/auth/cookie_secret
    name: cookie-secret
