apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: <<__external_secrets.backend_type__>>
  template:
    type: kubernetes.io/tls
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/istio-system/auth_ca_cert
    name: ca.crt
  - key: zpa-kubeflow-dev/istio-system/auth_cert
    name: tls.crt
  - key: zpa-kubeflow-dev/istio-system/auth_cert_pk
    name: tls.key
