apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.zscaler.com/kaas/at-argocd.git
    targetRevision: 890123456789/zpa-kubeflow-dev.my-domain
    path: distribution/kubecost-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
