apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: kubeflow-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: kubeflow.zpa-kubeflow-dev.my-domain
  dnsNames:
  - kubeflow.zpa-kubeflow-dev.my-domain
  - serving.zpa-kubeflow-dev.my-domain
  - "*.serving.zpa-kubeflow-dev.my-domain"
