apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
  - grafana.zpa-kubeflow-dev.my-domain
  - kiali.zpa-kubeflow-dev.my-domain
  - kubecost.zpa-kubeflow-dev.my-domain
