apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: mlflow
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/mlflow/rds_username
    name: RDS_USERNAME
  - key: zpa-kubeflow-dev/mlflow/rds_password
    name: RDS_PASSWORD
