kind: ConfigMap
apiVersion: v1
metadata:
  name: katib-rds-config
  namespace: kubeflow
data:
  DB_NAME: katib
  RDS_HOST: zpa-kubeflow-dev-instance.xzyabc123456.eu-central-1.rds.amazonaws.com
  RDS_PORT: "3306"
