apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: arn:aws:iam::966017130552:role/kf_argoflow_deployer
  data:
  - key: zpa-kubeflow-dev/monitoring/grafana_username
    name: admin-user
  - key: zpa-kubeflow-dev/monitoring/grafana_password
    name: admin-password
